#[configuration]
#local = "/home/jimfitz/go/src/github.com/integr8ly/integreatly-operator"
#org = "jfitzpat"
#temporary.reuse = true

[chain]
start = "current"
pre_release = "1234"

[new]
branch = "demo"
operator = "build"

