[configuration]
local = "/home/jimfitz/go/src/github.com/integr8ly/integreatly-operator"
org = "jfitzpat"
temporary.reuse = true

[chain]
start = "1.27.0-rc1"
pre_release = "1234"

[new]
branch = "demo"
